const pokemonArr = [
  { name: "bulbasaur", url: "https://tinyurl.com/ironhack-pokemons/1.svg" },
  { name: "ivysaur", url: "https://tinyurl.com/ironhack-pokemons/2.svg" },
  { name: "venusaur", url: "https://tinyurl.com/ironhack-pokemons/3.svg" },
  { name: "charmander", url: "https://tinyurl.com/ironhack-pokemons/4.svg" },
  { name: "charmeleon", url: "https://tinyurl.com/ironhack-pokemons/5.svg" },
  { name: "charizard", url: "https://tinyurl.com/ironhack-pokemons/6.svg" },
  { name: "squirtle", url: "https://tinyurl.com/ironhack-pokemons/7.svg" },
  { name: "wartortle", url: "https://tinyurl.com/ironhack-pokemons/8.svg" },
  { name: "blastoise", url: "https://tinyurl.com/ironhack-pokemons/9.svg" },
  { name: "caterpie", url: "https://tinyurl.com/ironhack-pokemons/10.svg" },
  { name: "metapod", url: "https://tinyurl.com/ironhack-pokemons/11.svg" },
  { name: "butterfree", url: "https://tinyurl.com/ironhack-pokemons/12.svg" },
  { name: "weedle", url: "https://tinyurl.com/ironhack-pokemons/13.svg" },
  { name: "kakuna", url: "https://tinyurl.com/ironhack-pokemons/14.svg" },
  { name: "beedrill", url: "https://tinyurl.com/ironhack-pokemons/15.svg" },
  { name: "pidgey", url: "https://tinyurl.com/ironhack-pokemons/16.svg" },
  { name: "pidgeotto", url: "https://tinyurl.com/ironhack-pokemons/17.svg" },
  { name: "pidgeot", url: "https://tinyurl.com/ironhack-pokemons/18.svg" },
  { name: "rattata", url: "https://tinyurl.com/ironhack-pokemons/19.svg" },
  { name: "raticate", url: "https://tinyurl.com/ironhack-pokemons/20.svg" },
  { name: "spearow", url: "https://tinyurl.com/ironhack-pokemons/21.svg" },
  { name: "fearow", url: "https://tinyurl.com/ironhack-pokemons/22.svg" },
  { name: "ekans", url: "https://tinyurl.com/ironhack-pokemons/23.svg" },
  { name: "arbok", url: "https://tinyurl.com/ironhack-pokemons/24.svg" },
  { name: "pikachu", url: "https://tinyurl.com/ironhack-pokemons/25.svg" },
  { name: "raichu", url: "https://tinyurl.com/ironhack-pokemons/26.svg" },
  { name: "sandshrew", url: "https://tinyurl.com/ironhack-pokemons/27.svg" },
  { name: "sandslash", url: "https://tinyurl.com/ironhack-pokemons/28.svg" },
  { name: "nidoran-f", url: "https://tinyurl.com/ironhack-pokemons/29.svg" },
  { name: "nidorina", url: "https://tinyurl.com/ironhack-pokemons/30.svg" },
  { name: "nidoqueen", url: "https://tinyurl.com/ironhack-pokemons/31.svg" },
  { name: "nidoran-m", url: "https://tinyurl.com/ironhack-pokemons/32.svg" },
  { name: "nidorino", url: "https://tinyurl.com/ironhack-pokemons/33.svg" },
  { name: "nidoking", url: "https://tinyurl.com/ironhack-pokemons/34.svg" },
  { name: "clefairy", url: "https://tinyurl.com/ironhack-pokemons/35.svg" },
  { name: "clefable", url: "https://tinyurl.com/ironhack-pokemons/36.svg" },
  { name: "vulpix", url: "https://tinyurl.com/ironhack-pokemons/37.svg" },
  { name: "ninetales", url: "https://tinyurl.com/ironhack-pokemons/38.svg" },
  { name: "jigglypuff", url: "https://tinyurl.com/ironhack-pokemons/39.svg" },
  { name: "wigglytuff", url: "https://tinyurl.com/ironhack-pokemons/40.svg" },
  { name: "zubat", url: "https://tinyurl.com/ironhack-pokemons/41.svg" },
  { name: "golbat", url: "https://tinyurl.com/ironhack-pokemons/42.svg" },
  { name: "oddish", url: "https://tinyurl.com/ironhack-pokemons/43.svg" },
  { name: "gloom", url: "https://tinyurl.com/ironhack-pokemons/44.svg" },
  { name: "vileplume", url: "https://tinyurl.com/ironhack-pokemons/45.svg" },
  { name: "paras", url: "https://tinyurl.com/ironhack-pokemons/46.svg" },
  { name: "parasect", url: "https://tinyurl.com/ironhack-pokemons/47.svg" },
  { name: "venonat", url: "https://tinyurl.com/ironhack-pokemons/48.svg" },
  { name: "venomoth", url: "https://tinyurl.com/ironhack-pokemons/49.svg" },
  { name: "diglett", url: "https://tinyurl.com/ironhack-pokemons/50.svg" },
  { name: "dugtrio", url: "https://tinyurl.com/ironhack-pokemons/51.svg" },
  { name: "meowth", url: "https://tinyurl.com/ironhack-pokemons/52.svg" },
  { name: "persian", url: "https://tinyurl.com/ironhack-pokemons/53.svg" },
  { name: "psyduck", url: "https://tinyurl.com/ironhack-pokemons/54.svg" },
  { name: "golduck", url: "https://tinyurl.com/ironhack-pokemons/55.svg" },
  { name: "mankey", url: "https://tinyurl.com/ironhack-pokemons/56.svg" },
  { name: "primeape", url: "https://tinyurl.com/ironhack-pokemons/57.svg" },
  { name: "growlithe", url: "https://tinyurl.com/ironhack-pokemons/58.svg" },
  { name: "arcanine", url: "https://tinyurl.com/ironhack-pokemons/59.svg" },
  { name: "poliwag", url: "https://tinyurl.com/ironhack-pokemons/60.svg" },
  { name: "poliwhirl", url: "https://tinyurl.com/ironhack-pokemons/61.svg" },
  { name: "poliwrath", url: "https://tinyurl.com/ironhack-pokemons/62.svg" },
  { name: "abra", url: "https://tinyurl.com/ironhack-pokemons/63.svg" },
  { name: "kadabra", url: "https://tinyurl.com/ironhack-pokemons/64.svg" },
  { name: "alakazam", url: "https://tinyurl.com/ironhack-pokemons/65.svg" },
  { name: "machop", url: "https://tinyurl.com/ironhack-pokemons/66.svg" },
  { name: "machoke", url: "https://tinyurl.com/ironhack-pokemons/67.svg" },
  { name: "machamp", url: "https://tinyurl.com/ironhack-pokemons/68.svg" },
  { name: "bellsprout", url: "https://tinyurl.com/ironhack-pokemons/69.svg" },
  { name: "weepinbell", url: "https://tinyurl.com/ironhack-pokemons/70.svg" },
  { name: "victreebel", url: "https://tinyurl.com/ironhack-pokemons/71.svg" },
  { name: "tentacool", url: "https://tinyurl.com/ironhack-pokemons/72.svg" },
  { name: "tentacruel", url: "https://tinyurl.com/ironhack-pokemons/73.svg" },
  { name: "geodude", url: "https://tinyurl.com/ironhack-pokemons/74.svg" },
  { name: "graveler", url: "https://tinyurl.com/ironhack-pokemons/75.svg" },
  { name: "golem", url: "https://tinyurl.com/ironhack-pokemons/76.svg" },
  { name: "ponyta", url: "https://tinyurl.com/ironhack-pokemons/77.svg" },
  { name: "rapidash", url: "https://tinyurl.com/ironhack-pokemons/78.svg" },
  { name: "slowpoke", url: "https://tinyurl.com/ironhack-pokemons/79.svg" },
  { name: "slowbro", url: "https://tinyurl.com/ironhack-pokemons/80.svg" },
  { name: "magnemite", url: "https://tinyurl.com/ironhack-pokemons/81.svg" },
  { name: "magneton", url: "https://tinyurl.com/ironhack-pokemons/82.svg" },
  { name: "farfetchd", url: "https://tinyurl.com/ironhack-pokemons/83.svg" },
  { name: "doduo", url: "https://tinyurl.com/ironhack-pokemons/84.svg" },
  { name: "dodrio", url: "https://tinyurl.com/ironhack-pokemons/85.svg" },
  { name: "seel", url: "https://tinyurl.com/ironhack-pokemons/86.svg" },
  { name: "dewgong", url: "https://tinyurl.com/ironhack-pokemons/87.svg" },
  { name: "grimer", url: "https://tinyurl.com/ironhack-pokemons/88.svg" },
  { name: "muk", url: "https://tinyurl.com/ironhack-pokemons/89.svg" },
  { name: "shellder", url: "https://tinyurl.com/ironhack-pokemons/90.svg" },
  { name: "cloyster", url: "https://tinyurl.com/ironhack-pokemons/91.svg" },
  { name: "gastly", url: "https://tinyurl.com/ironhack-pokemons/92.svg" },
  { name: "haunter", url: "https://tinyurl.com/ironhack-pokemons/93.svg" },
  { name: "gengar", url: "https://tinyurl.com/ironhack-pokemons/94.svg" },
  { name: "onix", url: "https://tinyurl.com/ironhack-pokemons/95.svg" },
  { name: "drowzee", url: "https://tinyurl.com/ironhack-pokemons/96.svg" },
  { name: "hypno", url: "https://tinyurl.com/ironhack-pokemons/97.svg" },
  { name: "krabby", url: "https://tinyurl.com/ironhack-pokemons/98.svg" },
  { name: "kingler", url: "https://tinyurl.com/ironhack-pokemons/99.svg" },
  { name: "voltorb", url: "https://tinyurl.com/ironhack-pokemons/100.svg/" },
  { name: "electrode", url: "https://tinyurl.com/ironhack-pokemons/101.svg/" },
  { name: "exeggcute", url: "https://tinyurl.com/ironhack-pokemons/102.svg/" },
  { name: "exeggutor", url: "https://tinyurl.com/ironhack-pokemons/103.svg/" },
  { name: "cubone", url: "https://tinyurl.com/ironhack-pokemons/104.svg/" },
  { name: "marowak", url: "https://tinyurl.com/ironhack-pokemons/105.svg/" },
  { name: "hitmonlee", url: "https://tinyurl.com/ironhack-pokemons/106.svg/" },
  { name: "hitmonchan", url: "https://tinyurl.com/ironhack-pokemons/107.svg/" },
  { name: "lickitung", url: "https://tinyurl.com/ironhack-pokemons/108.svg/" },
  { name: "koffing", url: "https://tinyurl.com/ironhack-pokemons/109.svg/" },
  { name: "weezing", url: "https://tinyurl.com/ironhack-pokemons/110.svg/" },
  { name: "rhyhorn", url: "https://tinyurl.com/ironhack-pokemons/111.svg/" },
  { name: "rhydon", url: "https://tinyurl.com/ironhack-pokemons/112.svg/" },
  { name: "chansey", url: "https://tinyurl.com/ironhack-pokemons/113.svg/" },
  { name: "tangela", url: "https://tinyurl.com/ironhack-pokemons/114.svg/" },
  { name: "kangaskhan", url: "https://tinyurl.com/ironhack-pokemons/115.svg/" },
  { name: "horsea", url: "https://tinyurl.com/ironhack-pokemons/116.svg/" },
  { name: "seadra", url: "https://tinyurl.com/ironhack-pokemons/117.svg/" },
  { name: "goldeen", url: "https://tinyurl.com/ironhack-pokemons/118.svg/" },
  { name: "seaking", url: "https://tinyurl.com/ironhack-pokemons/119.svg/" },
  { name: "staryu", url: "https://tinyurl.com/ironhack-pokemons/120.svg/" },
  { name: "starmie", url: "https://tinyurl.com/ironhack-pokemons/121.svg/" },
  { name: "mr-mime", url: "https://tinyurl.com/ironhack-pokemons/122.svg/" },
  { name: "scyther", url: "https://tinyurl.com/ironhack-pokemons/123.svg/" },
  { name: "jynx", url: "https://tinyurl.com/ironhack-pokemons/124.svg/" },
  { name: "electabuzz", url: "https://tinyurl.com/ironhack-pokemons/125.svg/" },
  { name: "magmar", url: "https://tinyurl.com/ironhack-pokemons/126.svg/" },
  { name: "pinsir", url: "https://tinyurl.com/ironhack-pokemons/127.svg/" },
  { name: "tauros", url: "https://tinyurl.com/ironhack-pokemons/128.svg/" },
  { name: "magikarp", url: "https://tinyurl.com/ironhack-pokemons/129.svg/" },
  { name: "gyarados", url: "https://tinyurl.com/ironhack-pokemons/130.svg/" },
  { name: "lapras", url: "https://tinyurl.com/ironhack-pokemons/131.svg/" },
  { name: "ditto", url: "https://tinyurl.com/ironhack-pokemons/132.svg/" },
  { name: "eevee", url: "https://tinyurl.com/ironhack-pokemons/133.svg/" },
  { name: "vaporeon", url: "https://tinyurl.com/ironhack-pokemons/134.svg/" },
  { name: "jolteon", url: "https://tinyurl.com/ironhack-pokemons/135.svg/" },
  { name: "flareon", url: "https://tinyurl.com/ironhack-pokemons/136.svg/" },
  { name: "porygon", url: "https://tinyurl.com/ironhack-pokemons/137.svg/" },
  { name: "omanyte", url: "https://tinyurl.com/ironhack-pokemons/138.svg/" },
  { name: "omastar", url: "https://tinyurl.com/ironhack-pokemons/139.svg/" },
  { name: "kabuto", url: "https://tinyurl.com/ironhack-pokemons/140.svg/" },
  { name: "kabutops", url: "https://tinyurl.com/ironhack-pokemons/141.svg/" },
  { name: "aerodactyl", url: "https://tinyurl.com/ironhack-pokemons/142.svg/" },
  { name: "snorlax", url: "https://tinyurl.com/ironhack-pokemons/143.svg/" },
  { name: "articuno", url: "https://tinyurl.com/ironhack-pokemons/144.svg/" },
  { name: "zapdos", url: "https://tinyurl.com/ironhack-pokemons/145.svg/" },
  { name: "moltres", url: "https://tinyurl.com/ironhack-pokemons/146.svg/" },
  { name: "dratini", url: "https://tinyurl.com/ironhack-pokemons/147.svg/" },
  { name: "dragonair", url: "https://tinyurl.com/ironhack-pokemons/148.svg/" },
  { name: "dragonite", url: "https://tinyurl.com/ironhack-pokemons/149.svg/" },
  { name: "mewtwo", url: "https://tinyurl.com/ironhack-pokemons/150.svg/" },
  { name: "mew", url: "https://tinyurl.com/ironhack-pokemons/151.svg/" }
];

// aqui insertaremos la data a la BD
// los seeds no se conectan con nuestro servidor

const Pokemon = require("../models/Pokemon.model");

// insertarla en la BD
const mongoose = require("mongoose");

mongoose
  .connect(
    "mongodb+srv://admin:admin@cluster0.iypz8.mongodb.net/?retryWrites=true&w=majority"
  )
  .then((response) => {
    console.log("conectados a la Dase de Datos");

    return Pokemon.insertMany(pokemonArr);
  })
  .then((response) => {
    console.log("Pokemons agregados correctamente");
    // hacer la desconeccion
    mongoose.connection.close();
  })
  .catch((err) => {
    console.log(err);
  });
